### ISSUE TITLE
Eslint rule

### ISSUE THREAD

**Issue by vanarok** [kalimah-apps/vite-plugin-vue-setup-inherit-attrs#1]
Need eslint rule for this plugin.

**Comment by abdul-alhasany** [comment]
What would the rule check for?

**Comment by vanarok** [comment]
https://eslint.vuejs.org/rules/no-duplicate-attr-inheritance.html#vue-no-duplicate-attr-inheritance.
That's what I mean. I apologize for not immediately attaching an example.

**Comment by abdul-alhasany** [comment]
This is a good idea. However:
1- I don't have time at the moment to develop a separate package for this. ESLint rules require the package name to have a certain convention which means I can't integrate it into this package.
2- The alternative is to create a pull request with [eslint-plugin-vue](https://eslint.vuejs.org/) but I doubt they will accept it since this is a separate plugin and not built-in functionality.

I might re-assess it in the future but for now I will close this.
